import assert from "node:assert/strict";
import {PreviewQueue, previewSlots} from "../web/preview-queue";
let credits = 0;
const queue = new PreviewQueue(() => credits++);
const chunk = () => new Float32Array(1024).fill(.25);
const left = new Float32Array(128), right = new Float32Array(128);
queue.push(0, chunk(), false);
queue.process(left, right);
assert.equal(queue.played, 0, "Must prefill before playback");
for (let i = 1; i < 8; i++) queue.push(i * 512, chunk(), false);
queue.paused = true; queue.process(left, right);
assert.equal(queue.played, 0);
queue.paused = false;
for (let i = 0; i < 32; i++) queue.process(left, right);
assert.equal(queue.played, 4096);
assert.equal(credits, 8);
queue.process(left, right);
assert.equal(queue.underruns, 1);
assert(left.every(value => value === 0));
queue.process(left, right);
assert.equal(queue.underruns, 1, "A stall counts once, not per callback");
queue.push(4096, new Float32Array(74).fill(.5), true);
queue.process(left, right);
assert.equal(queue.played, 4133);
assert.equal(queue.ended, true);
assert.equal(credits, 9);
assert(left.subarray(37).every(value => value === 0), "Partial tail must be silent");
assert.deepEqual(left, right);
const full = new PreviewQueue(() => {});
for (let i = 0; i < previewSlots; i++) full.push(i * 512, chunk(), false);
assert.equal(full.maximumBuffered, 8192);
assert.throws(() => full.push(8192, chunk(), false));
const invalid = new PreviewQueue(() => {});
assert.throws(() => invalid.push(512, chunk(), false), "Reject clock gaps");
assert.throws(() => invalid.push(0, new Float32Array([NaN, 0]), false));
assert.throws(() => invalid.push(0, new Float32Array(3), false));
console.log("Preview queue: bounded ownership, pause, underrun/rebuffer, final tail, invalid input pass");
