/* Generated by tools/generate_schema.py; do not edit. */
#ifndef FLUIDGRAIN_SCHEMA_H
#define FLUIDGRAIN_SCHEMA_H
typedef struct { double initial, minimum, maximum; int discrete; } FGParameter;
enum {
    FG_CONFIG_SCHEMA_VERSION = 0,
    FG_CONFIG_GRID_SIZE = 1,
    FG_CONFIG_EMITTER_COUNT = 2,
    FG_CONFIG_MAX_GRAINS = 3,
    FG_CONFIG_FLUID_HZ = 4,
    FG_CONFIG_SEED = 5,
    FG_CONFIG_BACKEND = 6,
    FG_CONFIG_BOUNDARY = 7,
    FG_CONFIG_SOURCE_LOOP = 8,
    FG_CONFIG_PRESSURE_ITERATIONS = 9,
    FG_CONFIG_VISCOSITY_ITERATIONS = 10,
    FG_CONFIG_INSTANCE_ID = 11,
    FG_CONFIG_PARTICLE_HZ = 12,
    FG_CONFIG_COUNT = 13
};
static const FGParameter fg_config_parameters[] = {
    {1, 1, 1, 1},
    {32, 16, 64, 1},
    {512, 1, 4096, 1},
    {512, 1, 4096, 1},
    {60, 30, 240, 0},
    {12345, 0, 16777215, 1},
    {0, 0, 1, 1},
    {0, 0, 0, 1},
    {0, 0, 1, 1},
    {64, 16, 256, 1},
    {16, 4, 64, 1},
    {0, 0, 16777215, 1},
    {240, 60, 1000, 0},
};
enum {
    FG_CONTROL_GAIN = 0,
    FG_CONTROL_GRAIN_RATE = 1,
    FG_CONTROL_GRAIN_MS = 2,
    FG_CONTROL_PITCH_RATIO = 3,
    FG_CONTROL_POSITION_CENTER = 4,
    FG_CONTROL_POSITION_SPAN = 5,
    FG_CONTROL_PITCH_DEPTH = 6,
    FG_CONTROL_STEREO_WIDTH = 7,
    FG_CONTROL_VISCOSITY = 8,
    FG_CONTROL_DRIVE = 9,
    FG_CONTROL_SWIRL = 10,
    FG_CONTROL_TURBULENCE = 11,
    FG_CONTROL_EDDY_SIZE = 12,
    FG_CONTROL_STRAIN_DRIVE = 13,
    FG_CONTROL_CONFINEMENT = 14,
    FG_CONTROL_INERTIA_MS = 15,
    FG_CONTROL_ATTRACTION = 16,
    FG_CONTROL_FLOW_SPEED = 17,
    FG_CONTROL_SPEED_TO_DENSITY = 18,
    FG_CONTROL_STRAIN_TO_DURATION = 19,
    FG_CONTROL_MAPPING_MIX = 20,
    FG_CONTROL_FREEZE = 21,
    FG_CONTROL_RESET = 22,
    FG_CONTROL_SCHEDULER = 23,
    FG_CONTROL_COUNT = 24
};
static const FGParameter fg_control_parameters[] = {
    {0.15, 0, 2, 0},
    {120, 0, 32000, 0},
    {80, 5, 500, 0},
    {1, 0.25, 4, 0},
    {0.5, 0, 1, 0},
    {1, 0, 1, 0},
    {7, 0, 24, 0},
    {1, 0, 1, 0},
    {0.0001, 0, 0.01, 0},
    {0.5, 0, 2, 0},
    {0.7, -1, 1, 0},
    {0.2, 0, 1, 0},
    {0.2, 0.05, 0.5, 0},
    {0, -1, 1, 0},
    {0, 0, 1, 0},
    {0, 0, 1000, 0},
    {0, 0, 1, 0},
    {1, 0, 4, 0},
    {0.5, 0, 1, 0},
    {0.5, 0, 1, 0},
    {1, 0, 1, 0},
    {0, 0, 1, 1},
    {0, 0, 1, 1},
    {1, 0, 1, 1},
};
enum {
    FG_STAT_LIVE_GRAINS = 0,
    FG_STAT_EMITTER_COUNT = 1,
    FG_STAT_EFFECTIVE_RATE = 2,
    FG_STAT_KINETIC_ENERGY = 3,
    FG_STAT_RMS_VORTICITY = 4,
    FG_STAT_RMS_STRAIN = 5,
    FG_STAT_RMS_DIVERGENCE = 6,
    FG_STAT_MAX_DIVERGENCE = 7,
    FG_STAT_FIELD_AGE_MS = 8,
    FG_STAT_VOICE_DROPS = 9,
    FG_STAT_SNAPSHOT_DROPS = 10,
    FG_STAT_NUMERIC_INTERVENTIONS = 11,
    FG_STAT_STATUS = 12,
    FG_STAT_BACKEND = 13,
    FG_STAT_SOURCE_LENGTH = 14,
    FG_STAT_SNAPSHOT_SEQUENCE = 15,
    FG_STAT_CONTROL_EVENTS = 16,
    FG_STAT_EPOCH = 17,
    FG_STAT_PRE_LIMITER_PEAK = 18,
    FG_STAT_CAP_DROPS = 19,
    FG_STAT_COUNT = 20
};
#define FG_STATUS_READY 1u
#define FG_STATUS_FROZEN 2u
#define FG_STATUS_STALE_FIELD 4u
#define FG_STATUS_PROVIDER_LOST 8u
#define FG_STATUS_CONTROLS_CLAMPED 16u
#define FG_STATUS_NUMERIC_INTERVENTION 32u
#define FG_STATUS_VOICE_OVERFLOW 64u
#define FG_STATUS_NOT_PREPARED 128u
#endif
