/* Generated by tools/generate_schema.py; do not edit. */
#ifndef NAVIERGRAIN_SCHEMA_H
#define NAVIERGRAIN_SCHEMA_H
typedef struct { double initial, minimum, maximum; int discrete; } NGParameter;
enum {
    NG_CONFIG_SCHEMA_VERSION = 0,
    NG_CONFIG_GRID_SIZE = 1,
    NG_CONFIG_EMITTER_COUNT = 2,
    NG_CONFIG_MAX_GRAINS = 3,
    NG_CONFIG_FLUID_HZ = 4,
    NG_CONFIG_SEED = 5,
    NG_CONFIG_BACKEND = 6,
    NG_CONFIG_BOUNDARY = 7,
    NG_CONFIG_SOURCE_LOOP = 8,
    NG_CONFIG_PRESSURE_ITERATIONS = 9,
    NG_CONFIG_VISCOSITY_ITERATIONS = 10,
    NG_CONFIG_INSTANCE_ID = 11,
    NG_CONFIG_PARTICLE_HZ = 12,
    NG_CONFIG_COUNT = 13
};
static const NGParameter ng_config_parameters[] = {
    {1, 1, 1, 1},
    {32, 16, 64, 1},
    {512, 1, 4096, 1},
    {512, 1, 4096, 1},
    {60, 30, 240, 0},
    {12345, 0, 16777215, 1},
    {0, 0, 1, 1},
    {0, 0, 0, 1},
    {0, 0, 1, 1},
    {64, 16, 256, 1},
    {16, 4, 64, 1},
    {0, 0, 16777215, 1},
    {240, 60, 1000, 0},
};
enum {
    NG_CONTROL_GAIN = 0,
    NG_CONTROL_GRAIN_RATE = 1,
    NG_CONTROL_GRAIN_MS = 2,
    NG_CONTROL_PITCH_RATIO = 3,
    NG_CONTROL_POSITION_CENTER = 4,
    NG_CONTROL_POSITION_SPAN = 5,
    NG_CONTROL_PITCH_DEPTH = 6,
    NG_CONTROL_STEREO_WIDTH = 7,
    NG_CONTROL_VISCOSITY = 8,
    NG_CONTROL_DRIVE = 9,
    NG_CONTROL_SWIRL = 10,
    NG_CONTROL_TURBULENCE = 11,
    NG_CONTROL_EDDY_SIZE = 12,
    NG_CONTROL_STRAIN_DRIVE = 13,
    NG_CONTROL_CONFINEMENT = 14,
    NG_CONTROL_INERTIA_MS = 15,
    NG_CONTROL_ATTRACTION = 16,
    NG_CONTROL_FLOW_SPEED = 17,
    NG_CONTROL_SPEED_TO_DENSITY = 18,
    NG_CONTROL_STRAIN_TO_DURATION = 19,
    NG_CONTROL_MAPPING_MIX = 20,
    NG_CONTROL_FREEZE = 21,
    NG_CONTROL_RESET = 22,
    NG_CONTROL_SCHEDULER = 23,
    NG_CONTROL_COUNT = 24
};
static const NGParameter ng_control_parameters[] = {
    {0.15, 0, 2, 0},
    {120, 0, 32000, 0},
    {80, 5, 500, 0},
    {1, 0.25, 4, 0},
    {0.5, 0, 1, 0},
    {1, 0, 1, 0},
    {7, 0, 24, 0},
    {1, 0, 1, 0},
    {0.0001, 0, 0.01, 0},
    {0.5, 0, 2, 0},
    {0.7, -1, 1, 0},
    {0.2, 0, 1, 0},
    {0.2, 0.05, 0.5, 0},
    {0, -1, 1, 0},
    {0, 0, 1, 0},
    {0, 0, 1000, 0},
    {0, 0, 1, 0},
    {1, 0, 4, 0},
    {0.5, 0, 1, 0},
    {0.5, 0, 1, 0},
    {1, 0, 1, 0},
    {0, 0, 1, 1},
    {0, 0, 1, 1},
    {1, 0, 1, 1},
};
enum {
    NG_STAT_LIVE_GRAINS = 0,
    NG_STAT_EMITTER_COUNT = 1,
    NG_STAT_EFFECTIVE_RATE = 2,
    NG_STAT_KINETIC_ENERGY = 3,
    NG_STAT_RMS_VORTICITY = 4,
    NG_STAT_RMS_STRAIN = 5,
    NG_STAT_RMS_DIVERGENCE = 6,
    NG_STAT_MAX_DIVERGENCE = 7,
    NG_STAT_FIELD_AGE_MS = 8,
    NG_STAT_VOICE_DROPS = 9,
    NG_STAT_SNAPSHOT_DROPS = 10,
    NG_STAT_NUMERIC_INTERVENTIONS = 11,
    NG_STAT_STATUS = 12,
    NG_STAT_BACKEND = 13,
    NG_STAT_SOURCE_LENGTH = 14,
    NG_STAT_SNAPSHOT_SEQUENCE = 15,
    NG_STAT_CONTROL_EVENTS = 16,
    NG_STAT_EPOCH = 17,
    NG_STAT_PRE_LIMITER_PEAK = 18,
    NG_STAT_CAP_DROPS = 19,
    NG_STAT_COUNT = 20
};
#define NG_STATUS_READY 1u
#define NG_STATUS_FROZEN 2u
#define NG_STATUS_STALE_FIELD 4u
#define NG_STATUS_PROVIDER_LOST 8u
#define NG_STATUS_CONTROLS_CLAMPED 16u
#define NG_STATUS_NUMERIC_INTERVENTION 32u
#define NG_STATUS_VOICE_OVERFLOW 64u
#define NG_STATUS_NOT_PREPARED 128u
#endif
