#!/usr/bin/env python3
"""Package the canonical C sources for the single-file browser opcode editor."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ('src/fluidgrain_field.c', 'src/fluidgrain_particles.c',
           'src/fluidgrain_resampler.c', 'src/fluidgrain_core.c',
           'src/fluidgrain_transport.c', 'src/fluidgrain_provider.c',
           'src/fluidgrain_browser.c', 'src/fluidgrain_pack.c', 'src/fluidgrain_opcode.c')


def amalgamate():
    seen = set()

    def expand(path):
        path = path.resolve()
        if path in seen:
            return ''
        seen.add(path)
        label = path.relative_to(ROOT).as_posix()
        lines = [f'#line 1 "{label}"\n']
        for number, line in enumerate(path.read_text().splitlines(keepends=True), 1):
            match = re.fullmatch(r'#include "([^"\n]+)"\s*', line)
            if match:
                name = match[1]
                candidates = (path.parent / name, ROOT / 'include' / name)
                dependency = next((p for p in candidates if p.is_file()), None)
                if dependency is None:
                    raise ValueError(f'Unresolved local include: {label}: {name}')
                lines.extend((expand(dependency), f'#line {number + 1} "{label}"\n'))
            else:
                lines.append(line)
        return ''.join(lines)

    return ('/* Generated by tools/amalgamate.py. Edit the canonical sources. */\n'
            '#ifndef BUILD_PLUGINS\n#define BUILD_PLUGINS\n#endif\n' +
            '\n'.join(expand(ROOT / name) for name in SOURCES))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'build/fluidgrain.c')
    args = parser.parse_args()
    source = amalgamate()
    # Match the pinned workbench's editor limit; fail before delivering a file
    # that its compiler cannot accept.
    if len(source.encode()) > 384 * 1024:
        raise ValueError('Amalgamation exceeds the 384 KiB packaging budget')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source)
    print(f'{args.output}: {len(source.encode())} bytes')


if __name__ == '__main__':
    main()
