#!/usr/bin/env python3
"""Generate the public wire contract. No third-party packages required."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    schema = json.loads((ROOT / 'schema/naviergrain-v1.json').read_text())
    c = ['/* Generated by tools/generate_schema.py; do not edit. */',
         '#ifndef NAVIERGRAIN_SCHEMA_H', '#define NAVIERGRAIN_SCHEMA_H',
         'typedef struct { double initial, minimum, maximum; int discrete; } NGParameter;']
    inc = ['; Generated by tools/generate_schema.py; do not edit.']
    ts = ['// Generated by tools/generate_schema.py; do not edit.']
    for group in ('config', 'control', 'stat'):
        entries = schema[group]
        c.append('enum {')
        names = {}
        for index, entry in enumerate(entries):
            name = 'NG_' + group.upper() + '_' + entry['name'].upper()
            c.append(f'    {name} = {index},')
            inc.append(f'#define {name} #{index}#')
            names[entry['name']] = index
        c.extend([f'    NG_{group.upper()}_COUNT = {len(entries)}', '};'])
        ts.append(f'export const {group} = {json.dumps(names, indent=2)} as const;')
        if group != 'stat':
            c.append(f'static const NGParameter ng_{group}_parameters[] = {{')
            for e in entries:
                c.append('    {%s, %s, %s, %d},' %
                         (e['default'], e['min'], e['max'], e.get('integer', False)))
            c.append('};')
            values = ', '.join(str(e['default']) for e in entries)
            inc.append(f'#define NG_{group.upper()}_DEFAULTS #{values}#')
            ts.append(f'export const {group}Defaults = [{values}] as const;')
    for index, name in enumerate(schema['status']):
        key = 'NG_STATUS_' + name.upper()
        c.append(f'#define {key} {1 << index}u')
        inc.append(f'#define {key} #{1 << index}#')
        ts.append(f'export const {key} = {1 << index};')
    c.append('#endif')
    return {'include/naviergrain_schema.h': '\n'.join(c) + '\n',
            'include/naviergrain.inc': '\n'.join(inc) + '\n',
            'web/naviergrain-schema.ts': '\n'.join(ts) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    drift = []
    for name, contents in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != contents:
                drift.append(name)
        else:
            path.write_text(contents)
    if drift:
        raise SystemExit('Generated schema drift: ' + ', '.join(drift))


if __name__ == '__main__':
    main()
