import {GrainPlanHost} from './grain-plan';
// Match the pinned DOM declarations used by gpu-solver.ts: device interfaces
// are present, but the WebGPU runtime constants are not declared there.
declare const GPUBufferUsage: Readonly<{MAP_READ: number; COPY_SRC: number;
  COPY_DST: number; STORAGE: number}>;
declare const GPUShaderStage: Readonly<{COMPUTE: number}>;
declare const GPUMapMode: Readonly<{READ: number}>;
/** Opt-in offline integration. One pending real C plan. Failed GPU batches are
 * regenerated by the production C reader in the SAME host, then committed once.
 * The default workbench/AudioWorklet path is unchanged. */
export class GrainRenderer {
  private device?: GPUDevice;
  private buffers: GPUBuffer[] = [];
  private bind?: GPUBindGroup;
  private pipelines?: GPUComputePipeline[];
  private packet?: GPUBuffer;
  private partial?: GPUBuffer;
  private output?: GPUBuffer;
  private staging?: GPUBuffer;
  private failed?: string;
  private closed = false;
  private busy = false;
  private epoch = 0;
  mode: 'gpu' | 'cpu' = 'cpu';
  fallbacks = 0;
  get failureReason(): string | undefined {return this.failed;}
  private constructor(readonly host: GrainPlanHost) {}
  static async create(host: GrainPlanHost, adapter: GPUAdapter | null, shader: string): Promise<GrainRenderer> {
    const renderer=new GrainRenderer(host);
    try {
      if(!adapter || !host.resources.length)throw new Error('GPU resources unavailable');
      const required=Math.max(host.packetCapacity,host.resources.byteLength,host.capacity*host.maxFrames*8);
      if(required>adapter.limits.maxStorageBufferBindingSize || required>adapter.limits.maxBufferSize)
        throw new Error('Prepared delivery exceeds GPU buffer limits');
      const device=await adapter.requestDevice({requiredLimits:{maxStorageBufferBindingSize:Math.max(134217728,required)}});renderer.device=device;
      device.lost.then(info=>{renderer.failed=info.message||'GPU device lost';});
      device.addEventListener('uncapturederror',event=>{renderer.failed=event.error.message;});
      const module=device.createShaderModule({code:shader});
      const info=await module.getCompilationInfo();
      if(info.messages.some(item=>item.type==='error'))throw new Error(info.messages.map(item=>item.message).join('\n'));
      const layout=device.createBindGroupLayout({entries:Array.from({length:4},(_,binding)=>({binding,
        visibility:GPUShaderStage.COMPUTE,buffer:{type:binding<2?'read-only-storage':'storage'}}))});
      const pipelineLayout=device.createPipelineLayout({bindGroupLayouts:[layout]});
      renderer.pipelines=await Promise.all(['grains','reduce'].map(entryPoint=>device.createComputePipelineAsync({layout:pipelineLayout,compute:{module,entryPoint}})));
      const buffer=(size:number,usage:number)=>{const result=device.createBuffer({size,usage});renderer.buffers.push(result);return result;};
      const resources=buffer(host.resources.byteLength,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST);
      renderer.packet=buffer(host.packetCapacity,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST);
      renderer.partial=buffer(host.capacity*host.maxFrames*8,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST);
      renderer.output=buffer(host.maxFrames*8,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);
      renderer.staging=buffer(host.maxFrames*8,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST);
      renderer.bind=device.createBindGroup({layout,entries:[resources,renderer.packet,renderer.partial,renderer.output].map((b,binding)=>({binding,resource:{buffer:b}}))});
      device.queue.writeBuffer(resources,0,host.resources);await device.queue.onSubmittedWorkDone();
      if(renderer.failed)throw new Error(renderer.failed);
      renderer.mode='gpu';
    } catch(error){renderer.useCpu(error);}
    return renderer;
  }
  private useCpu(error: unknown): void {
    this.failed=String(error);this.mode='cpu';this.fallbacks++;
    for(const buffer of this.buffers)buffer.destroy();this.buffers=[];this.device?.destroy();
  }
  /** Fault hooks are restricted to this explicit experimental host, not UI. */
  async render(frames=32,fault?: 'loss' | 'readback' | 'timeout'): Promise<{pcm:Float64Array; start:bigint; bytes:number; records:number; peakVoices:number; mode:string; captureMs:number; playbackMs:number; commitMs:number}> {
    if(this.closed||this.busy)throw new Error('Closed or busy grain renderer');
    this.busy=true;const epoch=this.epoch;let timer:ReturnType<typeof setTimeout>|undefined;
    try {
      // Detect loss before planning so an already-lost device causes no packing.
      if(this.mode==='gpu' && this.failed)this.useCpu(this.failed);
      const before=performance.now();const batch=this.host.capture(frames,this.mode==='gpu');const captureMs=performance.now()-before;
      const start=performance.now();let pcm:Float64Array|Float32Array;
      if(this.mode==='gpu') {
        try {
          if(this.failed||!batch.packet.length)throw new Error(this.failed||'Unpackable plan');
          const device=this.device!;if(fault==='loss')device.destroy();
          device.queue.writeBuffer(this.packet!,0,batch.packet);
          const encoder=device.createCommandEncoder();encoder.clearBuffer(this.partial!);
          const pass=encoder.beginComputePass();pass.setBindGroup(0,this.bind!);
          pass.setPipeline(this.pipelines![0]!);const segments=new DataView(batch.packet.buffer).getUint32(12,true);
          if(segments)pass.dispatchWorkgroups(Math.ceil(segments/64));
          pass.setPipeline(this.pipelines![1]!);pass.dispatchWorkgroups(frames);pass.end();
          encoder.copyBufferToBuffer(this.output!,0,this.staging!,0,frames*8);device.queue.submit([encoder.finish()]);
          if(fault==='readback')throw new Error('Injected readback rejection');
          const mapped=this.staging!.mapAsync(GPUMapMode.READ,0,frames*8);
          // The timeout hook holds delivery, not compute: late completion is
          // never allowed to replace the already committed CPU result.
          const delivered=fault==='timeout'?mapped.then(()=>new Promise<void>(()=>{})):mapped;
          await Promise.race([delivered,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('Grain readback timed out')),fault==='timeout'?5:5000);})]);
          if(timer)clearTimeout(timer);
          if(this.closed||epoch!==this.epoch)throw new Error('Grain render cancelled');
          if(this.failed)throw new Error(this.failed);
          pcm=new Float32Array(this.staging!.getMappedRange(0,frames*8)).slice();this.staging!.unmap();
          if(!pcm.every(Number.isFinite))throw new Error('Non-finite GPU output');
        } catch(error) {
          if(this.closed||epoch!==this.epoch)throw new Error('Grain render cancelled');
          this.useCpu(error);pcm=this.host.fallback(batch);
        }
      } else pcm=this.host.fallback(batch);
      if(this.closed||epoch!==this.epoch)throw new Error('Grain render cancelled');
      const playbackMs=performance.now()-start,commitStart=performance.now();
      const output=this.host.commit(batch,pcm);
      return {pcm:output,start:batch.start,bytes:batch.packet.byteLength,records:batch.records,peakVoices:batch.peakVoices,mode:this.mode,captureMs,playbackMs,commitMs:performance.now()-commitStart};
    } finally {if(timer)clearTimeout(timer);this.busy=false;}
  }
  destroy(): void {
    if(!this.closed){this.closed=true;this.epoch++;for(const buffer of this.buffers)buffer.destroy();this.device?.destroy();this.host.destroy();}
  }
}
