// Generated by tools/generate_schema.py; do not edit.
export const config = {
  "schema_version": 0,
  "grid_size": 1,
  "emitter_count": 2,
  "max_grains": 3,
  "fluid_hz": 4,
  "seed": 5,
  "backend": 6,
  "boundary": 7,
  "source_loop": 8,
  "pressure_iterations": 9,
  "viscosity_iterations": 10,
  "instance_id": 11,
  "particle_hz": 12
} as const;
export const configDefaults = [1, 32, 512, 512, 60, 12345, 0, 0, 0, 64, 16, 0, 240] as const;
export const control = {
  "gain": 0,
  "grain_rate": 1,
  "grain_ms": 2,
  "pitch_ratio": 3,
  "position_center": 4,
  "position_span": 5,
  "pitch_depth": 6,
  "stereo_width": 7,
  "viscosity": 8,
  "drive": 9,
  "swirl": 10,
  "turbulence": 11,
  "eddy_size": 12,
  "strain_drive": 13,
  "confinement": 14,
  "inertia_ms": 15,
  "attraction": 16,
  "flow_speed": 17,
  "speed_to_density": 18,
  "strain_to_duration": 19,
  "mapping_mix": 20,
  "freeze": 21,
  "reset": 22,
  "scheduler": 23
} as const;
export const controlDefaults = [0.15, 120, 80, 1, 0.5, 1, 7, 1, 0.0001, 0.5, 0.7, 0.2, 0.2, 0, 0, 0, 0, 1, 0.5, 0.5, 1, 0, 0, 1] as const;
export const stat = {
  "live_grains": 0,
  "emitter_count": 1,
  "effective_rate": 2,
  "kinetic_energy": 3,
  "rms_vorticity": 4,
  "rms_strain": 5,
  "rms_divergence": 6,
  "max_divergence": 7,
  "field_age_ms": 8,
  "voice_drops": 9,
  "snapshot_drops": 10,
  "numeric_interventions": 11,
  "status": 12,
  "backend": 13,
  "source_length": 14,
  "snapshot_sequence": 15,
  "control_events": 16,
  "epoch": 17,
  "pre_limiter_peak": 18,
  "cap_drops": 19
} as const;
export const NG_STATUS_READY = 1;
export const NG_STATUS_FROZEN = 2;
export const NG_STATUS_STALE_FIELD = 4;
export const NG_STATUS_PROVIDER_LOST = 8;
export const NG_STATUS_CONTROLS_CLAMPED = 16;
export const NG_STATUS_NUMERIC_INTERVENTION = 32;
export const NG_STATUS_VOICE_OVERFLOW = 64;
export const NG_STATUS_NOT_PREPARED = 128;
